[dev]
  targetPort = 4321

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[edge_functions]]
  path = "/get-events"
  function = "get-events"


[[edge_functions]]
  path = "/debug"
  function = "debug"