[dev]
  targetPort = 4321

[[edge_functions]]
  path = "/api/hello"
  function = "hello"

[[edge_functions]]
  path = "/api/get-events"
  function = "get-events"


[[edge_functions]]
  path = "/api/debug"
  function = "debug"