name: 'E2E Tests'

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  tests_e2e_netlify_prepare:
    name: Wait for deployment on Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retry Netlify Deployment
        run: |
          retries=5
          count=0
          until $(curl --output /dev/null --silent --head --fail https://deploy-preview-${{ github.event.pull_request.number }}--eventua11y.netlify.app/); do
            ((count++))
            if [ ${count} -ge ${retries} ]; then
              echo "Max retries reached, failing the job."
              exit 1
            fi
            echo "Netlify site not ready, retrying in 60 seconds..."
            sleep 60
          done
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}

  tests_e2e_netlify:
    needs: tests_e2e_netlify_prepare
    name: Run end-to-end tests on Netlify PR preview
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI and Allure Playwright
        run: |
          npm install -g allure-commandline --save-dev
          npm install --save-dev allure-playwright

      - name: Run tests and generate Allure results
        run: npx playwright test --reporter=line,allure-playwright
        env:
          BASE_URL: https://deploy-preview-${{ github.event.pull_request.number }}--eventua11y.netlify.app/

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report